name: likeplay
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^2.0.5
  shared_preferences: any
  gap: ^2.0.0
  http: any
  intl: ^0.17.0
  google_fonts: ^2.1.0
  responsive_framework: ^0.1.7
  email_validator: ^2.0.1
  url_launcher: ^6.1.7
  share_everywhere: ^0.0.1
  share_plus: any
  responsive_grid_list: ^1.3.1
  flutter_share: ^2.0.0
  url_strategy: ^0.2.0
  image_picker: ^0.8.6+2
  country_state_city_picker: ^1.2.8
  csc_picker: ^0.2.7
  file_picker: ^6.1.1
  chips_choice: ^3.0.0
  cached_network_image: ^3.2.3
  country_code_picker: ^3.0.0
  chat_bubbles: any
  fdottedline_nullsafety: ^2.0.1
  need_resume: ^1.0.7+1
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  firebase_messaging: ^14.2.1
  firebase_storage: ^11.0.8
  cloud_firestore: ^4.2.0
  bubble: ^1.1.9+1
  emoji_picker_flutter: ^1.5.4
  path_provider: ^2.0.15
  video_thumbnail: ^0.5.3
  chewie: ^1.2.2
  video_player: ^2.1.6
  flutter_otp_text_field: ^1.1.1
  flutter_facebook_auth: ^5.0.8
  mailto: ^2.0.0
  in_app_purchase: ^3.0.2
  flutter_local_notifications: ^9.0.3
#  firebase_crashlytics: any
  lottie: ^2.3.2
  camera: ^0.10.5+2
  camera_web: ^0.3.1+3
  infinite_scroll_pagination: ^3.2.0
  country_state_city_pro: ^0.0.3
  flutter_app_badger: ^1.5.0
  fluttertoast: ^8.0.8
  flutter_secure_storage: ^8.0.0
  flutter_image_compress:
  zego_uikit_prebuilt_call: ^4.2.1






  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides:
  zego_zpns: ^2.6.0+2
  zego_callkit: ^1.0.0+2


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish-SemiBold.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages

